// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfdoobecenjnuelpcjou.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmZG9vYmVjZW5qbnVlbHBjam91Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk0ODEwMDcsImV4cCI6MjA1NTA1NzAwN30.ZV-zRT-ACngBLWRrYjcLFdLsn122tDc1M_MKx4SYNUg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);